version: '3.9'

services:
  postgres:
    image: postgres:${POSTGRESQL_VERSION}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    ports:
      - "${POSTGRESQL_PORT_HOST}:${POSTGRESQL_PORT_CONTAINER}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "${KEYCLOAK_PORT_HOST}:${KEYCLOAK_PORT_CONTAINER}"
    restart: unless-stopped
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    networks:
      - local-keycloak

networks:
  local-keycloak:
volumes:
  postgres_data:
  keycloak_data: