
server:
  port: 8091

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-status-route
          uri: lb://resource-server
          predicates:
            - Path=/users/status/check
            - Method=GET
          filters:
#            - StripPrefix=1
            - RemoveRequestHeader=Cookie
        - id: albums
          uri: lb://album-service
          predicates:
            - Path=/albums
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
        - id: photos
          uri: lb://photo-service
          predicates:
            - Path=/photos
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
#        - id: photos
#          uri: http://localhost:8093
#          predicates:
#            - Path=/photos/albums/:albumId
#            - Method=GET
#          filters:
#            - RemoveRequestHeader=Cookie


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/